name: Lint

on:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request: {}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./src"
